package com.carex.leave.audit;

/** implementation.md §15.2 */
public enum AuditAction {
    LOGIN_SUCCEEDED, LOGIN_FAILED, DEMO_LOGIN,
    LEAVE_SUBMITTED, LEAVE_MANAGER_APPROVED, LEAVE_MANAGER_REJECTED, LEAVE_HR_APPROVED, LEAVE_HR_REJECTED,
    LEAVE_CANCELLED, LEAVE_ESCALATED, ESCALATION_RUN_MANUAL,
    CONFLICT_FLAGGED, CONFLICT_ACKNOWLEDGED,
    BALANCE_CREATED, BALANCE_CONSUMED, BALANCE_RESTORED,
    TRANSITION_DENIED, ACCESS_DENIED,
    ASSISTANT_PROPOSAL_CREATED, DEMO_RESET
}
